"""create secrets table

Revision ID: b1f2d6535a21
Revises: 296081feebfa
Create Date: 2026-09-26 17:19:12.916880
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b1f2d6535a21"
down_revision: str | Sequence[str] | None = "296081feebfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(length=12), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("encryption_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "encryption_version > 0",
            name=op.f("ck_secrets_encryption_version_positive"),
        ),
        sa.CheckConstraint(
            "key_version > 0", name=op.f("ck_secrets_key_version_positive")
        ),
        sa.CheckConstraint(
            "octet_length(ciphertext) >= 16", name=op.f("ck_secrets_ciphertext_length")
        ),
        sa.CheckConstraint(
            "octet_length(nonce) = 12", name=op.f("ck_secrets_nonce_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_secrets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secrets")),
        sa.UniqueConstraint(
            "key_version", "nonce", name=op.f("uq_secrets_key_version")
        ),
    )
    op.create_index(op.f("ix_secrets_user_id"), "secrets", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secrets_user_id"), table_name="secrets")
    op.drop_table("secrets")
    # ### end Alembic commands ###
